name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"   # roda a cada 6 horas
  workflow_dispatch:        # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: MariaClaraSampaio
          outputs: dist/snake.svg
          color_snake: "#ff69b4"   # rosa choque (cobrinha)
          color_dots: "#ADD8E6"    # azul bebê (quadradinhos com contribuições)
          color_empty: "#FFC0CB"   # rosa bebê (quadradinhos vazios)
          grid_size: 20

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
